
import random
from .targets import Targets
from .modifiers import Modifiers


class Effect():

    """ Effect of an item """

    EFFECT_ABSOLUTE_SHIELD = 0
    EFFECT_ABSOLUTE_VULNERABILITY = 1
    EFFECT_AFTEREFFECT = 2
    EFFECT_ALLY_KILLED_TO_AGILITY = 3
    EFFECT_ANTIDOTE = 4
    EFFECT_ATTRACT = 5
    EFFECT_BOOST_MAX_LIFE = 6
    EFFECT_BUFF_AGILITY = 7
    EFFECT_BUFF_MP = 8
    EFFECT_BUFF_RESISTANCE = 9
    EFFECT_BUFF_STRENGTH = 10
    EFFECT_BUFF_TP = 11
    EFFECT_BUFF_WISDOM = 12
    EFFECT_CRITICAL_TO_HEAL = 13
    EFFECT_DAMAGE = 14
    EFFECT_DAMAGE_RETURN = 15
    EFFECT_DAMAGE_TO_ABSOLUTE_SHIELD = 16
    EFFECT_DAMAGE_TO_STRENGTH = 17
    EFFECT_DEBUFF = 18
    EFFECT_HEAL = 19
    EFFECT_INVERT = 20
    EFFECT_KILL = 21
    EFFECT_KILL_TO_TP = 22
    EFFECT_LIFE_DAMAGE = 23
    EFFECT_MODIFIER_IRREDUCTIBLE = 24
    EFFECT_MODIFIER_MULTIPLIED_BY_TARGETS = 25
    EFFECT_MODIFIER_NOT_REPLACEABLE = 26
    EFFECT_MODIFIER_ON_CASTER = 27
    EFFECT_MODIFIER_STACKABLE = 28
    EFFECT_MOVED_TO_MP = 29
    EFFECT_NOVA_DAMAGE = 30
    EFFECT_NOVA_DAMAGE_TO_MAGIC = 31
    EFFECT_NOVA_VITALITY = 32
    EFFECT_POISON = 33
    EFFECT_POISON_TO_SCIENCE = 34
    EFFECT_PROPAGATION = 35
    EFFECT_PUSH = 36
    EFFECT_RAW_ABSOLUTE_SHIELD = 37
    EFFECT_RAW_BUFF_AGILITY = 38
    EFFECT_RAW_BUFF_MAGIC = 39
    EFFECT_RAW_BUFF_MP = 40
    EFFECT_RAW_BUFF_POWER = 41
    EFFECT_RAW_BUFF_RESISTANCE = 42
    EFFECT_RAW_BUFF_SCIENCE = 43
    EFFECT_RAW_BUFF_STRENGTH = 44
    EFFECT_RAW_BUFF_TP = 45
    EFFECT_RAW_BUFF_WISDOM = 46
    EFFECT_RAW_HEAL = 47
    EFFECT_RAW_RELATIVE_SHIELD = 48
    EFFECT_RELATIVE_SHIELD = 49
    EFFECT_REMOVE_SHACKLES = 50
    EFFECT_REPEL = 51
    EFFECT_RESURRECT = 52
    EFFECT_SHACKLE_AGILITY = 53
    EFFECT_SHACKLE_MAGIC = 54
    EFFECT_SHACKLE_MP = 55
    EFFECT_SHACKLE_STRENGTH = 56
    EFFECT_SHACKLE_TP = 57
    EFFECT_SHACKLE_WISDOM = 58
    EFFECT_STEAL_ABSOLUTE_SHIELD = 59
    EFFECT_SUMMON = 60
    EFFECT_TARGET_ALLIES = 61
    EFFECT_TARGET_CASTER = 62
    EFFECT_TARGET_ENEMIES = 63
    EFFECT_TARGET_NON_SUMMONS = 64
    EFFECT_TARGET_SUMMONS = 65
    EFFECT_TELEPORT = 66
    EFFECT_VULNERABILITY = 67

    EFFECTS = [
        EFFECT_ABSOLUTE_SHIELD,
        EFFECT_ABSOLUTE_VULNERABILITY,
        EFFECT_AFTEREFFECT,
        EFFECT_ALLY_KILLED_TO_AGILITY,
        EFFECT_ANTIDOTE,
        EFFECT_ATTRACT,
        EFFECT_BOOST_MAX_LIFE,
        EFFECT_BUFF_AGILITY,
        EFFECT_BUFF_MP,
        EFFECT_BUFF_RESISTANCE,
        EFFECT_BUFF_STRENGTH,
        EFFECT_BUFF_TP,
        EFFECT_BUFF_WISDOM,
        EFFECT_CRITICAL_TO_HEAL,
        EFFECT_DAMAGE,
        EFFECT_DAMAGE_RETURN,
        EFFECT_DAMAGE_TO_ABSOLUTE_SHIELD,
        EFFECT_DAMAGE_TO_STRENGTH,
        EFFECT_DEBUFF,
        EFFECT_HEAL,
        EFFECT_INVERT,
        EFFECT_KILL,
        EFFECT_KILL_TO_TP,
        EFFECT_LIFE_DAMAGE,
        EFFECT_MODIFIER_IRREDUCTIBLE,
        EFFECT_MODIFIER_MULTIPLIED_BY_TARGETS,
        EFFECT_MODIFIER_NOT_REPLACEABLE,
        EFFECT_MODIFIER_ON_CASTER,
        EFFECT_MODIFIER_STACKABLE,
        EFFECT_MOVED_TO_MP,
        EFFECT_NOVA_DAMAGE,
        EFFECT_NOVA_DAMAGE_TO_MAGIC,
        EFFECT_NOVA_VITALITY,
        EFFECT_POISON,
        EFFECT_POISON_TO_SCIENCE,
        EFFECT_PROPAGATION,
        EFFECT_PUSH,
        EFFECT_RAW_ABSOLUTE_SHIELD,
        EFFECT_RAW_BUFF_AGILITY,
        EFFECT_RAW_BUFF_MAGIC,
        EFFECT_RAW_BUFF_MP,
        EFFECT_RAW_BUFF_POWER,
        EFFECT_RAW_BUFF_RESISTANCE,
        EFFECT_RAW_BUFF_SCIENCE,
        EFFECT_RAW_BUFF_STRENGTH,
        EFFECT_RAW_BUFF_TP,
        EFFECT_RAW_BUFF_WISDOM,
        EFFECT_RAW_HEAL,
        EFFECT_RAW_RELATIVE_SHIELD,
        EFFECT_RELATIVE_SHIELD,
        EFFECT_REMOVE_SHACKLES,
        EFFECT_REPEL,
        EFFECT_RESURRECT,
        EFFECT_SHACKLE_AGILITY,
        EFFECT_SHACKLE_MAGIC,
        EFFECT_SHACKLE_MP,
        EFFECT_SHACKLE_STRENGTH,
        EFFECT_SHACKLE_TP,
        EFFECT_SHACKLE_WISDOM,
        EFFECT_STEAL_ABSOLUTE_SHIELD,
        EFFECT_SUMMON,
        EFFECT_TARGET_ALLIES,
        EFFECT_TARGET_CASTER,
        EFFECT_TARGET_ENEMIES,
        EFFECT_TARGET_NON_SUMMONS,
        EFFECT_TARGET_SUMMONS,
        EFFECT_TELEPORT,
        EFFECT_VULNERABILITY
    ]


    def __init__(self, type, value_min, value_max, turns, targets, modifiers):
        self.type = type
        self.value_min = value_min
        self.value_max = value_max
        self.turns = turns
        self.targets = targets
        self.modifiers = modifiers


    def __str__(self):
        toPrint = ""
        toPrint += f"[Effect] :: Type={self.type} :: Value_Min={self.value_min} :: Value_Max={self.value_max} :: Turns={self.turns} :: Targets={self.targets} :: Modifiers={self.modifiers}"
        return toPrint


    @classmethod
    def sample(cls):
        type = random.choice(Effect.EFFECTS)
        value_min = random.randint(0, 50)
        value_max = value_min + random.randint(0, 50)
        turns = random.randint(0, 5)
        targets = Targets.sample()
        modifiers = Modifiers.sample()
        return cls(type, value_min, value_max, turns, targets, modifiers)



if (__name__ == "__main__"):
    effect = Effect.sample()
    print(effect)
