
from abc import ABC

class Effect(ABC):

    """ Abstract class containing effects """

    EFFECT_ABSOLUTE_SHIELD = 0
    EFFECT_ABSOLUTE_VULNERABILITY = 1
    EFFECT_AFTEREFFECT = 2
    EFFECT_ALLY_KILLED_TO_AGILITY = 3
    EFFECT_ANTIDOTE = 4
    EFFECT_ATTRACT = 5
    EFFECT_BOOST_MAX_LIFE = 6
    EFFECT_BUFF_AGILITY = 7
    EFFECT_BUFF_MP = 8
    EFFECT_BUFF_RESISTANCE = 9
    EFFECT_BUFF_STRENGTH = 10
    EFFECT_BUFF_TP = 11
    EFFECT_BUFF_WISDOM = 12
    EFFECT_CRITICAL_TO_HEAL = 13
    EFFECT_DAMAGE = 14
    EFFECT_DAMAGE_RETURN = 15
    EFFECT_DAMAGE_TO_ABSOLUTE_SHIELD = 16
    EFFECT_DAMAGE_TO_STRENGTH = 17
    EFFECT_DEBUFF = 18
    EFFECT_HEAL = 19
    EFFECT_INVERT = 20
    EFFECT_KILL = 21
    EFFECT_KILL_TO_TP = 22
    EFFECT_LIFE_DAMAGE = 23
    EFFECT_MODIFIER_IRREDUCTIBLE = 24
    EFFECT_MODIFIER_MULTIPLIED_BY_TARGETS = 25
    EFFECT_MODIFIER_NOT_REPLACEABLE = 26
    EFFECT_MODIFIER_ON_CASTER = 27
    EFFECT_MODIFIER_STACKABLE = 28
    EFFECT_MOVED_TO_MP = 29
    EFFECT_NOVA_DAMAGE = 30
    EFFECT_NOVA_DAMAGE_TO_MAGIC = 31
    EFFECT_NOVA_VITALITY = 32
    EFFECT_POISON = 33
    EFFECT_POISON_TO_SCIENCE = 34
    EFFECT_PROPAGATION = 35
    EFFECT_PUSH = 36
    EFFECT_RAW_ABSOLUTE_SHIELD = 37
    EFFECT_RAW_BUFF_AGILITY = 38
    EFFECT_RAW_BUFF_MAGIC = 39
    EFFECT_RAW_BUFF_MP = 40
    EFFECT_RAW_BUFF_POWER = 41
    EFFECT_RAW_BUFF_RESISTANCE = 42
    EFFECT_RAW_BUFF_SCIENCE = 43
    EFFECT_RAW_BUFF_STRENGTH = 44
    EFFECT_RAW_BUFF_TP = 45
    EFFECT_RAW_BUFF_WISDOM = 46
    EFFECT_RAW_HEAL = 47
    EFFECT_RAW_RELATIVE_SHIELD = 48
    EFFECT_RELATIVE_SHIELD = 49
    EFFECT_REMOVE_SHACKLES = 50
    EFFECT_REPEL = 51
    EFFECT_RESURRECT = 52
    EFFECT_SHACKLE_AGILITY = 53
    EFFECT_SHACKLE_MAGIC = 54
    EFFECT_SHACKLE_MP = 55
    EFFECT_SHACKLE_STRENGTH = 56
    EFFECT_SHACKLE_TP = 57
    EFFECT_SHACKLE_WISDOM = 58
    EFFECT_STEAL_ABSOLUTE_SHIELD = 59
    EFFECT_SUMMON = 60
    EFFECT_TARGET_ALLIES = 61
    EFFECT_TARGET_CASTER = 62
    EFFECT_TARGET_ENEMIES = 63
    EFFECT_TARGET_NON_SUMMONS = 64
    EFFECT_TARGET_SUMMONS = 65
    EFFECT_TELEPORT = 66
    EFFECT_VULNERABILITY = 67


    def __init__(self, type, min, max, turns, targets, modifiers):
        self.type = type
        self.min = min
        self.max = max
        self.turns = turns
        self.targets = targets
        self.modifiers = modifiers
