
from item import Item

class Chip(Item):

    """ Class chips """

    # TODO : Put everything in a .csv
    CHIP_ACCELERATION = 0
    CHIP_ADRENALINE = 1
    CHIP_ALTERATION = 2
    CHIP_ANTIDOTE = 3
    CHIP_ARMOR = 4
    CHIP_ARMORING = 5
    CHIP_ARSENIC = 6
    CHIP_BALL_AND_CHAIN = 7
    CHIP_BANDAGE = 8
    CHIP_BARK = 9
    CHIP_BOXING_GLOVE = 10
    CHIP_BRAINWASHING = 11
    CHIP_BRAMBLE = 12
    CHIP_BURNING = 13
    CHIP_CARAPACE = 14
    CHIP_COLLAR = 15
    CHIP_COVETOUSNESS = 16
    CHIP_COVID = 17
    CHIP_CRUSHING = 18
    CHIP_CURE = 19
    CHIP_DESINTEGRATION = 20
    CHIP_DEVIL_STRIKE = 21
    CHIP_DOME = 22
    CHIP_DOPING = 23
    CHIP_DRIP = 24
    CHIP_ELEVATION = 25
    CHIP_FEROCITY = 26
    CHIP_FERTILIZER = 27
    CHIP_FIRE_BULB = 28
    CHIP_FLAME = 29
    CHIP_FLASH = 30
    CHIP_FORTRESS = 31
    CHIP_FRACTURE = 32
    CHIP_GRAPPLE = 33
    CHIP_HEALER_BULB = 34
    CHIP_HELMET = 35
    CHIP_ICE = 36
    CHIP_ICEBERG = 37
    CHIP_ICED_BULB = 38
    CHIP_INVERSION = 39
    CHIP_JUMP = 40
    CHIP_KNOWLEDGE = 41
    CHIP_LEATHER_BOOTS = 42
    CHIP_LIBERATION = 43
    CHIP_LIGHTNING = 44
    CHIP_LIGHTNING_BULB = 45
    CHIP_LOAM = 46
    CHIP_MANUMISSION = 47
    CHIP_METALLIC_BULB = 48
    CHIP_METEORITE = 49
    CHIP_MIRROR = 50
    CHIP_MOTIVATION = 51
    CHIP_MUTATION = 52
    CHIP_PEBBLE = 53
    CHIP_PLAGUE = 54
    CHIP_PLASMA = 55
    CHIP_PRECIPITATION = 56
    CHIP_PRISM = 57
    CHIP_PROTEIN = 58
    CHIP_PUNISHMENT = 59
    CHIP_PUNY_BULB = 60
    CHIP_RAGE = 61
    CHIP_RAMPART = 62
    CHIP_REFLEXES = 63
    CHIP_REGENERATION = 64
    CHIP_REMISSION = 65
    CHIP_REPOTTING = 66
    CHIP_RESURRECTION = 67
    CHIP_ROCK = 68
    CHIP_ROCKFALL = 69
    CHIP_ROCKY_BULB = 70
    CHIP_SAVANT_BULB = 71
    CHIP_SERUM = 72
    CHIP_SEVEN_LEAGUE_BOOTS = 73
    CHIP_SHIELD = 74
    CHIP_SHOCK = 75
    CHIP_SLOW_DOWN = 76
    CHIP_SOLIDIFICATION = 77
    CHIP_SOPORIFIC = 78
    CHIP_SPARK = 79
    CHIP_STALACTITE = 80
    CHIP_STEROID = 81
    CHIP_STRETCHING = 82
    CHIP_TACTICIAN_BULB = 83
    CHIP_TELEPORTATION = 84
    CHIP_THERAPY = 85
    CHIP_THORN = 86
    CHIP_TOXIN = 87
    CHIP_TRANQUILIZER = 88
    CHIP_TRANSMUTATION = 89
    CHIP_VACCINE = 90
    CHIP_VAMPIRIZATION = 91
    CHIP_VENOM = 92
    CHIP_WALL = 93
    CHIP_WARM_UP = 94
    CHIP_WHIP = 95
    CHIP_WINGED_BOOTS = 96
    CHIP_WIZARD_BULB = 97
    CHIP_WIZARDRY = 98


    self.__init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
